include:
 - project: acc-co/devops/python/acc-py-devtools
   file: acc_py_devtools/templates/gitlab-ci/python.yml

variables:
  project_name: be_bi_pyqt_project_manager


# A full installation of project, tested with pytest.
Test Full Install:
  image: gitlab-registry.cern.ch/acc-co/accsoft/gui/accsoft-gui-pyqt-distro/acc-py-pyqt:ci
  script:
   - python -m pip install .[all]
   - run_headless python -m pytest --log-cli-level=DEBUG --random-order --junitxml=report.xml --cov-report html:coverage --cov-report term-missing:skip-covered --cov=${project_name} -vx --color=yes
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
   name: coverage-report
   paths:
    - coverage
   when: on_success
   expire_in: 1 month
   reports:
    junit: report.xml


# A push of the source distribution to the acc-py PyPI, only on git tag.
Release on Tag:
  extends: .acc_py_release_sdist


# A push of the source distribution to the acc-py PyPI, to be triggered manually.
Manual Release:
  extends: ._acc_py_release_sdist_base
  when: manual
