include:
 - project: acc-co/devops/python/acc-py-devtools
   file: acc_py_devtools/templates/gitlab-ci/python.yml

variables:
  project_name: bipy_gui_manager


# A full installation of project, tested with pytest.
Test Full Install:
  extends: .acc_py_base
  stage: test
  before_script:
   - yum install -y openldap-devel python-devel
   - pip install -e ${project_root}[test]
   - pip install pytest-cov pytest-random-order
  script:
   # Run the unit-tests with coverage output.
   - pytest ${project_root} --cov=${project_name} --junitxml=report.xml --random-order
  artifacts:
   expire_in: 30 days
   reports:
    junit: report.xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  except:
   changes:
    - "*.md"
